### ISSUE TITLE
Cannot find any entity

### ISSUE THREAD

**Issue by nikaiwolf** [Allerter/spotify-telegram-sync#5]
ive tried different ways of doing the telegram id. channel id is only 9 digits and added -1000 & -100 to front of it to get the 13 required digits. that didnt work either. running on heroku.

> 2021-05-13T19:35:28.185153+00:00 app[worker.1]: sts - INFO - Starting up...
2021-05-13T19:35:28.297692+00:00 app[worker.1]: telethon.network.mtprotosender - INFO - Connecting to 149.154.175.52:443/TcpFull...
2021-05-13T19:35:28.324586+00:00 app[worker.1]: telethon.network.mtprotosender - INFO - Connection to 149.154.175.52:443/TcpFull complete!
2021-05-13T19:35:28.517844+00:00 app[worker.1]: Traceback (most recent call last):
2021-05-13T19:35:28.517847+00:00 app[worker.1]:   File "spotify_telegram_sync/bot.py", line 651, in <module>
2021-05-13T19:35:28.517848+00:00 app[worker.1]:     loop.run_until_complete(prepare_clients(queue))
2021-05-13T19:35:28.517848+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2021-05-13T19:35:28.517849+00:00 app[worker.1]:     return future.result()
2021-05-13T19:35:28.517850+00:00 app[worker.1]:   File "spotify_telegram_sync/bot.py", line 567, in prepare_clients
2021-05-13T19:35:28.517850+00:00 app[worker.1]:     clients["telegram_channel"] = await telegram.get_input_entity(
2021-05-13T19:35:28.517851+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/telethon/client/users.py", line 432, in get_input_entity
2021-05-13T19:35:28.518492+00:00 app[worker.1]:     await self._get_entity_from_string(peer))
2021-05-13T19:35:28.518493+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/telethon/client/users.py", line 569, in _get_entity_from_string
2021-05-13T19:35:28.518996+00:00 app[worker.1]:     raise ValueError(
2021-05-13T19:35:28.518997+00:00 app[worker.1]: ValueError: Cannot find any entity corresponding to "-1000#########"
2021-05-13T19:35:28.829883+00:00 heroku[worker.1]: Process exited with status 1
2021-05-13T19:35:28.931325+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by allerter** [comment]
Your channel ID is most likely valid, but since the `TELEGRAM_CHANNEL` is passed to `telegram.get_input_entity` as a string and [not as an integer](https://t.me/TelethonChat/333933), it results in that error.
We can easily solve this by trying to convert `TELEGRAM_CHANNEL` to int if possible. You can send a PR if you're interested. Please let me know.

**Comment by nikaiwolf** [comment]
i setup an autoforwarder to send the links to a different channel where i have the full channel id available. still no luck.

**Comment by allerter** [comment]
I'm not sure I understand. As I said, it doesn't matter if the channel ID is correct or not. Since it's passed as a string to `get_input_entity`, it fails. Right now, you can either use the channel's username or an invite link.

**Comment by nikaiwolf** [comment]
okay i used an invite link now spotify refresh token is expired. ran the spotify refresh token again and still getting that error

**Comment by nikaiwolf** [comment]
> 2021-05-13T20:34:57.206048+00:00 app[worker.1]: sts - INFO - Starting up...
2021-05-13T20:34:57.385323+00:00 app[worker.1]: telethon.network.mtprotosender - INFO - Connecting to 149.154.175.52:443/TcpFull...
2021-05-13T20:34:57.412911+00:00 app[worker.1]: telethon.network.mtprotosender - INFO - Connection to 149.154.175.52:443/TcpFull complete!
2021-05-13T20:34:57.746676+00:00 app[worker.1]: spotify_telegram_sync/bot.py:593: RuntimeWarning: coroutine 'MessageMethods.send_message' was never awaited
2021-05-13T20:34:57.746746+00:00 app[worker.1]:   telegram.send_message("me", msg)
2021-05-13T20:34:57.746752+00:00 app[worker.1]: RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2021-05-13T20:34:57.746758+00:00 app[worker.1]: Your Spotify refresh token is expired. Replace it with a new one. Original error message: '400 invalid_grant: Invalid refresh token'
2021-05-13T20:34:58.336772+00:00 heroku[worker.1]: Process exited with status 1
2021-05-13T20:34:58.436823+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by allerter** [comment]
As the logs suggest, your refresh token is somehow invalid. Please double check your Spotify credentials: `SPOTIFY_CLIENT_ID`, `SPOTIFY_CLIENT_SECRET`, `SPOTIFY_REFRESH_TOKEN`.

**Comment by nikaiwolf** [comment]
still nope. even deleted the spotify app on the developers dashboard and remade it. it needs the full example.com link right?

**Comment by allerter** [comment]
Yes. Something like: `https://example.com/callback?code=some_stringg&state=some_string`

**Comment by nikaiwolf** [comment]
yeah ive done that. ill do it again just to make sure

**Comment by nikaiwolf** [comment]
nope. also copy pasted the id and secret again

**Comment by allerter** [comment]
I just tried again with my own refresh token and no issues. Could you please explain what you do step by step?

**Comment by nikaiwolf** [comment]
run 'spotify_refresh_roken.py'
copy paste 'client_id' and 'client_secret_id'
agree to the spotify agreement
copy paste link into heroku 'spotify_refresh_token'

**Comment by allerter** [comment]
That's wrong. You should paste the link in the console where you ran `spotify_refresh_roken.py`. Then you will get a refresh token.

**Comment by nikaiwolf** [comment]
ohhhhh. just did that and it closes the window. then realized i was doing that in the python window not cmd. doing it in cmd gave me the code and now its working. thank you for the help. and heroku will just run it 24/7?

**Comment by allerter** [comment]
Yes, until the dyno runs out of juice if you have a free account (Heroku will notify you by email prior). You can view your remaining hours on the [billing page](https://dashboard.heroku.com/account/billing). Normally Heroku gives 500 hours for free accounts. You can increase this by entering your credit card info to 1000 hours (no charges applied) which might be enough.

**Comment by nikaiwolf** [comment]
okay sweet. and thats monthly hours in heroku?

**Comment by allerter** [comment]
Yes

**Comment by nikaiwolf** [comment]
oh thats not bad at all. and will this pull previous spotify links? or only new ones?

**Comment by allerter** [comment]
Initially, there are no tracks in the database, so it will get all tracks in the playlist and from there whenever a new one is added. You can read more about the user bot's functionality in the [How it Works section of the README](https://github.com/allerter/spotify-telegram-sync#how-it-works).

**Comment by nikaiwolf** [comment]
thank you for the help.

**Comment by nikaiwolf** [comment]
think i did something else wrong. playlist hasnt updated

**Comment by allerter** [comment]
The logs are your friend. Look at them and see what went wrong.

**Comment by nikaiwolf** [comment]
> 2021-05-14T19:25:24.476135+00:00 heroku[worker.1]: Restarting
2021-05-14T19:25:24.492840+00:00 heroku[worker.1]: State changed from up to starting
2021-05-14T19:25:25.758828+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-05-14T19:25:25.838236+00:00 app[worker.1]: sts - INFO - Received exit signal SIGTERM...
2021-05-14T19:25:25.876375+00:00 app[worker.1]: telethon.network.mtprotosender - INFO - Disconnecting from 149.154.175.52:443/TcpFull...
2021-05-14T19:25:25.879540+00:00 app[worker.1]: telethon.network.mtprotosender - INFO - Disconnection from 149.154.175.52:443/TcpFull complete!
2021-05-14T19:25:25.884499+00:00 app[worker.1]: sts - INFO - Cleaning up before exiting...
2021-05-14T19:25:25.886749+00:00 app[worker.1]: sts - ERROR - Telegram error while cleaning up: Cannot send requests while disconnected
2021-05-14T19:25:25.886970+00:00 app[worker.1]: telethon.network.mtprotosender - INFO - Not disconnecting (already have no connection)
2021-05-14T19:25:26.006277+00:00 app[worker.1]: /app/.heroku/python/lib/python3.8/asyncio/base_events.py:1744: RuntimeWarning: coroutine 'exception_handler' was never awaited
2021-05-14T19:25:26.006297+00:00 app[worker.1]:   self._exception_handler(self, context)
2021-05-14T19:25:26.006298+00:00 app[worker.1]: RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2021-05-14T19:25:26.385282+00:00 heroku[worker.1]: Process exited with status 0
2021-05-14T19:25:36.981321+00:00 heroku[worker.1]: Starting process with command `python3 spotify_telegram_sync/bot.py`
2021-05-14T19:25:37.676045+00:00 heroku[worker.1]: State changed from starting to up
2021-05-14T19:25:42.862015+00:00 app[worker.1]: sts - INFO - Starting up...
2021-05-14T19:25:42.964478+00:00 app[worker.1]: telethon.network.mtprotosender - INFO - Connecting to 149.154.175.52:443/TcpFull...
2021-05-14T19:25:42.991768+00:00 app[worker.1]: telethon.network.mtprotosender - INFO - Connection to 149.154.175.52:443/TcpFull complete!
2021-05-14T19:25:44.342820+00:00 app[worker.1]: sts - INFO - Update playlist: ✔️ | Update bio: ✔️
2021-05-14T19:25:44.342990+00:00 app[worker.1]: sts - INFO - Check Telegram: ✔️
2021-05-14T19:25:44.346798+00:00 app[worker.1]: sts.check_deleted - INFO - Checking Telegram admin log for deleted tracks...
2021-05-14T19:25:45.438607+00:00 app[worker.1]: telethon.client.downloads - INFO - Starting direct file download in chunks of 65536 at 0, stride 65536
2021-05-14T19:25:45.590681+00:00 app[worker.1]: telethon.client.uploads - INFO - Uploading file of 66748 bytes in 1 chunks of 131072
2021-05-14T19:25:45.689515+00:00 app[worker.1]: sts.update_bios - INFO - Checking playback...
2021-05-14T19:25:45.790415+00:00 app[worker.1]: sts.update_bios - INFO - Playback is paused.

**Comment by nikaiwolf** [comment]
its a group channel on telegram with friends and they all post songs. do i need to be admin in the channel?

**Comment by allerter** [comment]
Note that the logs on Heroku are cleaned after a while. If you want to retain the logs, you have to use a log hosting service or some other solution which is out of the scope of this user bot.

You do need to be an admin in `TELEGRAM_CHANNEL` with the proper permissions for your configurations.

**Comment by nikaiwolf** [comment]
okay sweet. they'll make me an admin no problem. yeah i restarted it and thats the log i just posted. do i have it setup correctly for building the playlist from telegram?

**Comment by allerter** [comment]
Yes, the logs tell you what you have enabled:
```
Update playlist: ✔️| Update bio: ✔️
Check Telegram: ✔️
```

**Comment by nikaiwolf** [comment]
okay sweet. does it matter what type of chat it is on telegram? channel or group?

**Comment by nikaiwolf** [comment]
i have a channel setup with me as admin and a pinned message. thats all working and updating. i have a couple people adding spotify links to the channel to test.

**Comment by nikaiwolf** [comment]
think i got it working.

**Comment by allerter** [comment]
Great. I'm going to lock the conversation in this issue now. If you had any other problems, feel free to open a new issue.
